name: CSE Intern Crawl
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        run: python cse_companies_crawler.py

      - name: Update data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto-update data'
          file_pattern: 'data_histories/* companies.json'
          commit_user_name: 'GitHub Action'
          commit_user_email: 'action@github.com'